# 상세검색시 DB 내용 지시서 파일
"""add search_suggestion_cache table

Revision ID: 4607e2ffebcb
Revises: 
Create Date: 2026-08-23 17:25:09.315858
"""
from alembic import op
import sqlalchemy as sa


revision = '4607e2ffebcb'
down_revision = None
branch_labels = None
depends_on = None

# 마이그레이션 적용 시
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_suggestion_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lang')
    )
    # ### end Alembic commands ###

# 마이그레이션 취소시 테이블 삭제 장치
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_suggestion_cache')
    # ### end Alembic commands ###
